"""Names filled in by gen_bar.py, so a remix runs its own bar."""
NAME = "Borealis"
SLUG = "borealis"
VERSION = "1.0"
APP_ID = "org.borealis.bar"
TWEAKS_ID = "org.borealis.tweaks"
BUS = "org.borealis.Bar"
PATH = "/Bar"
INTERFACE = "org.borealis.Bar1"
LNF_DARK = "Borealis-Dark"
LNF_LIGHT = "Borealis-Light"
AURORA = "org.borealis.aurora"
