"""KDE color schemes: BorealisDark.colors / BorealisLight.colors."""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from tokens import DARK, IDS, LIGHT, kde, mix  # noqa: E402

KEYS = ("BackgroundAlternate", "BackgroundNormal", "DecorationFocus",
        "DecorationHover", "ForegroundActive", "ForegroundInactive",
        "ForegroundLink", "ForegroundNegative", "ForegroundNeutral",
        "ForegroundNormal", "ForegroundPositive", "ForegroundVisited")


def group(p, bg, bg_alt, **over):
    g = {
        "BackgroundAlternate": bg_alt,
        "BackgroundNormal": bg,
        "DecorationFocus": p["accent"],
        "DecorationHover": p["accent_hover"],
        "ForegroundActive": p["secondary"],
        "ForegroundInactive": p["text_inactive"],
        "ForegroundLink": p["link"],
        "ForegroundNegative": p["negative"],
        "ForegroundNeutral": p["neutral"],
        "ForegroundNormal": p["text"],
        "ForegroundPositive": p["positive"],
        "ForegroundVisited": p["visited"],
    }
    g.update(over)
    return g


def scheme(p):
    dark = p["is_dark"]
    on = p["on_accent"]
    sel_muted = mix(p["accent"], on, 0.55)
    groups = {
        "Colors:Window": group(p, p["window"], p["header"]),
        "Colors:View": group(p, p["view"], mix(p["view"], p["window"], 0.55)),
        "Colors:Button": group(p, p["button"], p["button_alt"]),
        "Colors:Header": group(p, p["header"], p["window"]),
        "Colors:Header][Inactive": group(p, p["header_inactive"], p["header"]),
        "Colors:Tooltip": group(p, p["tooltip"], p["window"]),
        "Colors:Selection": group(
            p, p["accent"], mix(p["accent"], p["window"], 0.45),
            ForegroundNormal=on, ForegroundActive=on, ForegroundInactive=sel_muted,
            ForegroundLink=mix(on, "#1f2a8a" if dark else "#e8ecff", 0.7),
            ForegroundVisited=mix(on, "#4a2a8a" if dark else "#f0e4ff", 0.7),
            ForegroundNegative="#8a1027" if dark else "#ffd6de",
            ForegroundNeutral="#6b4400" if dark else "#ffe7b8",
            ForegroundPositive="#0a5c4e" if dark else "#c9fff4",
            DecorationHover=p["accent_hover"]),
    }
    # Complementary is always the dark surface (OSDs, lock/logout screens)
    cp = DARK
    groups["Colors:Complementary"] = group(cp, cp["base"], cp["view"])

    disabled_color = p["view"]
    lines = [
        "# Borealis color scheme — generated by gen_colors.py",
        "# SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        "[ColorEffects:Disabled]",
        f"Color={kde(disabled_color)}",
        "ColorAmount=0",
        "ColorEffect=0",
        "ContrastAmount=0.65" if dark else "ContrastAmount=0.5",
        "ContrastEffect=1",
        "IntensityAmount=0.1",
        "IntensityEffect=2",
        "",
        "[ColorEffects:Inactive]",
        "ChangeSelectionColor=true",
        f"Color={kde(p['text_inactive'])}",
        "ColorAmount=0.025",
        "ColorEffect=2",
        "ContrastAmount=0.1",
        "ContrastEffect=2",
        "Enable=false",
        "IntensityAmount=0",
        "IntensityEffect=0",
        "",
    ]
    for name in ("Colors:Button", "Colors:Complementary", "Colors:Header",
                 "Colors:Header][Inactive", "Colors:Selection", "Colors:Tooltip",
                 "Colors:View", "Colors:Window"):
        lines.append(f"[{name}]")
        lines += [f"{k}={kde(groups[name][k])}" for k in KEYS]
        lines.append("")
    sid = IDS["colors_dark"] if dark else IDS["colors_light"]
    lines += [
        "[General]",
        f"ColorScheme={sid}",
        f"Name={p['title']}",
        "shadeSortColumn=true",
        "",
        "[KDE]",
        "contrast=4",
        "",
        "[WM]",
        f"activeBackground={kde(p['header'])}",
        f"activeBlend={kde(p['text'])}",
        f"activeForeground={kde(p['text'])}",
        f"inactiveBackground={kde(p['header_inactive'])}",
        f"inactiveBlend={kde(p['text_inactive'])}",
        f"inactiveForeground={kde(p['text_inactive'])}",
        "",
    ]
    return sid, "\n".join(lines)


def build(out_root):
    d = os.path.join(out_root, "color-schemes")
    os.makedirs(d, exist_ok=True)
    ids = []
    for p in (DARK, LIGHT):
        sid, text = scheme(p)
        with open(os.path.join(d, sid + ".colors"), "w") as f:
            f.write(text)
        ids.append(sid)
    return ids


if __name__ == "__main__":
    print(build(sys.argv[1]))
