"""Borealis colours for GTK4/libadwaita apps.

libadwaita ignores GTK themes and only takes an accent from the desktop portal
(snapped to one of its nine presets: Borealis would become plain blue). This
stylesheet, imported from ~/.config/gtk-4.0/gtk.css, maps the Borealis palette
onto libadwaita 1.9. One file holds both variants: light at top level, dark
under @media (prefers-color-scheme: dark), which GTK re-evaluates live when
Plasma switches between Borealis Light and Dark.

Every colour is written twice:
  * as a legacy named colour (@define-color window_bg_color ...): libadwaita's
    :root variables alias these, its @theme_* compatibility colours derive from
    them, and apps' own stylesheets still use them;
  * as the documented CSS variable (--window-bg-color ...), which also covers
    colours with no named alias (--overview-*, standalone --accent-color).
GTK3 apps already follow the KDE scheme via Breeze-GTK.
"""
import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(__file__))
from tokens import DARK, LIGHT, contrast, ensure_contrast, mix  # noqa: E402

FILENAME = "borealis-libadwaita.css"

# Breeze's GTK4 theme (plain, non-libadwaita apps) defines these names itself;
# leave them alone and set only the variable form.
SKIP_NAMED = {"success_color", "warning_color", "error_color"}

# Hairlines are currentColor at --border-opacity (Adwaita: 15 %); these land
# close to the Borealis border colour. High contrast must be restated because a
# user :root rule beats libadwaita's own @media (prefers-contrast: more) block.
BORDER_OPACITY = {"light": "10%", "dark": "12%", "hc": "50%"}


def on(bg):
    """White or ink text, whichever reads better on bg."""
    return max(("#ffffff", "#0b0f19"), key=lambda c: contrast(c, bg))


def mapping(p):
    """libadwaita colour name (underscore form) -> hex for one variant."""
    dark = p["is_dark"]
    text = p["text"]
    sidebar = p["header"]
    secondary = mix(sidebar, p["window"], 0.5)
    card = p["button"] if dark else p["view"]
    # standalone colours are used as text on any surface: check the worst one
    surfaces = (p["window"], p["view"], p["header"], sidebar, card, p["tooltip"])

    def text_on_all(c):
        worst = min(surfaces, key=lambda s: contrast(c, s))
        return ensure_contrast(c, worst)

    return {
        "window_bg_color": p["window"],
        "window_fg_color": text,
        "view_bg_color": p["view"],
        "view_fg_color": text,
        # libadwaita mixes the headerbar border at --border-opacity, so it is
        # the text colour (as in Adwaita), not a finished border colour
        "headerbar_bg_color": p["header"],
        "headerbar_fg_color": text,
        "headerbar_border_color": text,
        "headerbar_backdrop_color": p["header_inactive"],
        "sidebar_bg_color": sidebar,
        "sidebar_fg_color": text,
        "sidebar_backdrop_color": mix(sidebar, p["window"], 0.5),
        "sidebar_border_color": p["border"],
        "secondary_sidebar_bg_color": secondary,
        "secondary_sidebar_fg_color": text,
        "secondary_sidebar_backdrop_color": mix(secondary, p["window"], 0.5),
        "secondary_sidebar_border_color": p["border"],
        "card_bg_color": card,
        "card_fg_color": text,
        "dialog_bg_color": p["window"],
        "dialog_fg_color": text,
        "popover_bg_color": p["tooltip"],
        "popover_fg_color": text,
        "thumbnail_bg_color": card,
        "thumbnail_fg_color": text,
        "accent_bg_color": p["accent"],
        "accent_fg_color": p["on_accent"],
        "accent_color": text_on_all(p["link"]),
        "destructive_bg_color": p["negative"],
        "destructive_fg_color": on(p["negative"]),
        "destructive_color": text_on_all(p["negative"]),
        "success_bg_color": p["positive"],
        "success_fg_color": on(p["positive"]),
        "success_color": text_on_all(p["positive"]),
        "warning_bg_color": p["neutral"],
        "warning_fg_color": on(p["neutral"]),
        "warning_color": text_on_all(p["neutral"]),
        "error_bg_color": p["negative"],
        "error_fg_color": on(p["negative"]),
        "error_color": text_on_all(p["negative"]),
    }


def extra_vars(p, key):
    """Variables with no legacy named colour."""
    return {
        "--overview-bg-color": p["base"],
        "--overview-fg-color": p["text"],
        "--border-opacity": BORDER_OPACITY[key],
    }


def var(name):
    return "--" + name.replace("_", "-")


def stylesheet():
    light, dark = mapping(LIGHT), mapping(DARK)
    nw = max(map(len, light)) + 1
    vw = max(len(var(k)) for k in light) + 2
    out = [
        "/* Borealis for GTK4 / libadwaita, generated by gen_gtk.py.",
        " * Imported from ~/.config/gtk-4.0/gtk.css (KDE keeps that line; it never",
        " * writes this file). Light values first, dark under the media query. */",
        "",
        "/* 1. Named colours: libadwaita's variables, its @theme_* colours and apps' own",
        " *    stylesheets all read these. */",
    ]
    out += [f"@define-color {k.ljust(nw)}{v};" for k, v in light.items() if k not in SKIP_NAMED]
    out += ["", "@media (prefers-color-scheme: dark) {"]
    out += [f"  @define-color {k.ljust(nw)}{v};" for k, v in dark.items() if k not in SKIP_NAMED]
    out += ["}", "", "/* 2. The same colours as libadwaita (>= 1.6) CSS variables. */", ":root {"]
    rows = [(var(k), v) for k, v in light.items()] + list(extra_vars(LIGHT, "light").items())
    out += [f"  {(k + ':').ljust(vw)} {v};" for k, v in rows]
    out += ["}", "", "@media (prefers-color-scheme: dark) {", "  :root {"]
    rows = [(var(k), v) for k, v in dark.items()] + list(extra_vars(DARK, "dark").items())
    out += [f"    {(k + ':').ljust(vw)} {v};" for k, v in rows]
    out += ["  }", "}", "",
            "@media (prefers-contrast: more) {",
            f"  :root {{ --border-opacity: {BORDER_OPACITY['hc']}; }}",
            "}", ""]
    return "\n".join(out)


def build(out_root):
    base = os.path.join(out_root, "gtk", "borealis")
    if os.path.exists(base):
        shutil.rmtree(base)
    os.makedirs(base)
    with open(os.path.join(base, FILENAME), "w") as f:
        f.write(stylesheet())
    return base


if __name__ == "__main__":
    print(build(sys.argv[1]))
