"""Borealis for the GRUB menu — the last stock-looking screen before Plasma.

Renders the aurora as the menu background, a rounded accent highlight for the
selected entry, and bakes a .pf2 font (GRUB can't read TTFs). Installed by
`install-system.sh --grub`, which also switches GRUB to graphics mode.
"""
import os
import shutil
import subprocess
import sys

sys.path.insert(0, os.path.dirname(__file__))
from tokens import DARK, IDS, NAME, SLUG, mix, rgb  # noqa: E402

from PIL import Image, ImageDraw, ImageEnhance, ImageFilter  # noqa: E402

W, H = 1920, 1200
FONT_CANDIDATES = [
    "/usr/share/fonts/rsms-inter-fonts/Inter-Regular.ttf",
    "/usr/share/fonts/rsms-inter-fonts/Inter-Medium.ttf",
    "/usr/share/fonts/abattis-cantarell-vf-fonts/Cantarell-VF.otf",
    "/usr/share/fonts/dejavu-sans-fonts/DejaVuSans.ttf",
]
FONT_NAME = f"{NAME} Regular"
SIZES = (20, 28)          # menu entries, title


def background(night):
    """The aurora, dimmed and blurred a little so menu text stays readable."""
    img = night.convert("RGB").resize((W, H), Image.LANCZOS)
    img = img.filter(ImageFilter.GaussianBlur(3))
    img = ImageEnhance.Brightness(img).enhance(0.55)
    shade = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(shade)
    for i in range(H):                      # darker towards the middle rows
        d.line([(0, i), (W, i)], fill=int(90 * min(1.0, abs(i / H - 0.5) * 2) ** 2))
    return Image.composite(img, ImageEnhance.Brightness(img).enhance(1.25), shade)


def nine_slice(base, color, radius=10, alpha=210, border=None):
    """Write <base>_{c,n,s,e,w,ne,nw,se,sw}.png for a rounded pixmap style."""
    size = radius * 2 + 2
    tile = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(tile)
    d.rounded_rectangle([0, 0, size - 1, size - 1], radius=radius,
                        fill=rgb(color) + (alpha,),
                        outline=(rgb(border) + (255,)) if border else None,
                        width=2 if border else 0)
    r = radius
    pieces = {
        "nw": (0, 0, r, r), "n": (r, 0, r + 1, r), "ne": (size - r, 0, size, r),
        "w": (0, r, r, r + 1), "c": (r, r, r + 1, r + 1), "e": (size - r, r, size, r + 1),
        "sw": (0, size - r, r, size), "s": (r, size - r, r + 1, size),
        "se": (size - r, size - r, size, size),
    }
    out = {}
    for name, box in pieces.items():
        out[f"{base}_{name}.png"] = tile.crop(box)
    return out


def theme_txt():
    p = DARK
    return f"""# {NAME} for GRUB — generated by gen_grub.py
title-text: ""
desktop-image: "background.png"
desktop-color: "{p['base']}"
terminal-font: "{FONT_NAME} {SIZES[0]}"
terminal-left: "8%"
terminal-top: "12%"
terminal-width: "84%"
terminal-height: "70%"
terminal-border: "0"

+ label {{
    top = 14%
    left = 0
    width = 100%
    align = "center"
    id = "__title__"
    text = "{NAME}"
    font = "{FONT_NAME} {SIZES[1]}"
    color = "{p['text']}"
}}

+ boot_menu {{
    left = 25%
    top = 26%
    width = 50%
    height = 46%
    item_font = "{FONT_NAME} {SIZES[0]}"
    item_color = "{p['text_inactive']}"
    selected_item_color = "{p['text']}"
    item_height = 44
    item_padding = 14
    item_spacing = 6
    icon_width = 0
    icon_height = 0
    item_icon_space = 0
    selected_item_pixmap_style = "select_*.png"
    scrollbar = true
    scrollbar_width = 6
    scrollbar_thumb = "thumb_*.png"
}}

+ progress_bar {{
    id = "__timeout__"
    left = 33%
    top = 78%
    width = 34%
    height = 6
    show_text = false
    bar_style = "track_*.png"
    highlight_style = "fill_*.png"
}}

+ label {{
    top = 82%
    left = 0
    width = 100%
    align = "center"
    id = "__timeout__"
    text = "Starting in %d s"
    font = "{FONT_NAME} {SIZES[0]}"
    color = "{p['text_inactive']}"
}}

+ label {{
    top = 92%
    left = 0
    width = 100%
    align = "center"
    text = "↑↓ choose    Enter start    E edit    C console"
    font = "{FONT_NAME} {SIZES[0]}"
    color = "{mix(p['text_inactive'], p['base'], 0.35)}"
}}
"""


def make_font(dest):
    """GRUB needs .pf2; bake one from the first font we can find."""
    src = next((f for f in FONT_CANDIDATES if os.path.exists(f)), None)
    tool = shutil.which("grub2-mkfont") or shutil.which("grub-mkfont")
    if not src or not tool:
        return []
    made = []
    for size in SIZES:
        out = os.path.join(dest, f"{SLUG.lower()}-{size}.pf2")
        r = subprocess.run([tool, "-s", str(size), "-n", f"{FONT_NAME} {size}", "-o", out, src],
                           capture_output=True, text=True)
        if r.returncode == 0:
            made.append(os.path.basename(out))
    return made


def build(out_root, night):
    base = os.path.join(out_root, "grub", "themes", IDS["plymouth"])
    if os.path.exists(base):
        shutil.rmtree(base)
    os.makedirs(base)
    background(night).save(os.path.join(base, "background.png"))
    p = DARK
    art = {}
    art.update(nine_slice("select", p["accent"], radius=10, alpha=70, border=p["accent"]))
    art.update(nine_slice("thumb", p["accent"], radius=3, alpha=180))
    art.update(nine_slice("track", p["border"], radius=3, alpha=140))
    art.update(nine_slice("fill", p["accent"], radius=3, alpha=255))
    for name, img in art.items():
        img.save(os.path.join(base, name))
    with open(os.path.join(base, "theme.txt"), "w") as f:
        f.write(theme_txt())
    fonts = make_font(base)
    if not fonts:
        print("  (no grub2-mkfont or font file: the menu will use GRUB's built-in font)")
    return base


if __name__ == "__main__":
    from gen_wallpaper import render_night
    print(build(sys.argv[1], render_night()))
